-- AlterTable
ALTER TABLE `comment` ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `post` ADD COLUMN `likes` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `user` ADD COLUMN `subscribers` INTEGER NOT NULL DEFAULT 0;
